### ISSUE TITLE
Agent: sk-ssh-ed25519 not implemented

### ISSUE THREAD

**Issue by jtagcat** [Foxboron/ssh-tpm-agent#26]
Went overtime and ran out of time to get ssh-tpm-agent working.

Mentioned this in https://github.com/Foxboron/ssh-tpm-agent/pull/24:
```
... level=DEBUG msg="%s not a TPM sealed key: %v\n" /r/c/ssh/hh-8192_ecdsa.tpm="tpm-ssh: unsupported key type \"TPM EC PRIVATE KEY\"
```

^ fixed this by generating a key using trunk, not v0.1.0

Now:
```
$ ssh-tpm-keygen
[---]
```

ssh config:
```
Match OriginalHost github.com
  IdentityAgent /run/user/1000/ssh-tpm-agent.sock
  IdentityFile /r/c/ssh/hh-8192_ecdsa.tpm
  IdentitiesOnly yes
```

***

```
$ ssh git@github.com
...
Load key "/r/c/ssh/hh-8192_ecdsa.tpm": error in libcrypto
```
```
Oct 14 17:03:20 hh-8192 ssh-tpm-agent[1984892]: time=2023-10-14T17:03:20.844+03:00 level=INFO msg="agent 25: agent: not implemented: \"sk-ssh-ed25519@openssh.com\""
```

This happens with RSA key as well.

**Comment by Foxboron** [comment]
This seems weird. Why would ssh pass an `sk` key to the agent? Do you have other things running or another `ssh-agent` configed?

**Comment by jtagcat** [comment]
I have a configuration that can't really get much more complex :upside_down_face:: config with global options, hosts config with targets, git-id.conf (manual version of https://github.com/jtagcat/git-id/). Multiple yubikeys + each host gets touched by multiple sections...

Turns out the problem was caused by using 'private key' (.tpm), not pubkey with `IdentityFile` in the config. I think adding this to README is noisy, search should be able to lead people here.

Main symptom: `Load key "/home/jc/.ssh/hh-8192_rsa.tpm": error in libcrypto` after SSH.

**Comment by Foxboron** [comment]
Right, if you look at the README example you can actually see that the public key is used for `IdentityFile`. But this is not elaborated on in the README.

https://github.com/Foxboron/ssh-tpm-agent#ssh-config
