### ISSUE TITLE
host key functionality fails

### ISSUE THREAD

**Issue by sevenrats** [Foxboron/ssh-tpm-agent#30]
everything seems to work ok but when I restart sshd:
Dec 10 01:08:32 host systemd[1]: Starting OpenBSD Secure Shell server...
Dec 10 01:08:32 host sshd[24703]: Unable to load host key "/etc/ssh/ssh_tpm_host_ecdsa_key.pub": error in libcrypto
Dec 10 01:08:32 host sshd[24703]: Unable to load host key "/etc/ssh/ssh_tpm_host_rsa_key.pub": error in libcrypto
Dec 10 01:08:32 host sshd[24704]: Unable to load host key "/etc/ssh/ssh_tpm_host_ecdsa_key.pub": error in libcrypto
Dec 10 01:08:32 host sshd[24704]: Unable to load host key "/etc/ssh/ssh_tpm_host_rsa_key.pub": error in libcrypto
Dec 10 01:08:32 host sshd[24704]: Server listening on 0.0.0.0 port 22.
Dec 10 01:08:32 host sshd[24704]: Server listening on :: port 22.
Dec 10 01:08:32 host systemd[1]: Started OpenBSD Secure Shell server.

**Comment by Foxboron** [comment]
This is actually expected. The error message just means libcrypto failed or parse them, but they are still forwarded to the agent.
It is very confusing and I spent quite a while thinking it didn't work.

Have you validated if the host keys are served or not?

**Comment by sevenrats** [comment]
oh, wow, they are being served.
so cool!
will i be able to sign these public keys with my ssh pki now? that would be insanely cool!

**Comment by Foxboron** [comment]
>will i be able to sign these public keys with my ssh pki now? that would be insanely cool!

I'm unsure how that looks like or how it works. If you give an example it can probably be supported or worked on.

**Comment by sevenrats** [comment]
it appears to work out of the box. just follow the instructions for host keys, then take the public key created by those scripts and sign it with your host CA to create a cert, and add "HostCertificate /path/to/the/certificate" underneath the newly created HostKey directives.  any ssh client which trusts your host pki will trust the host certificate automatically.

**Comment by Foxboron** [comment]
Cool, glad it works :)
