### ISSUE TITLE
ssh-tpm-agent --print socket prints value of $SSH_AUTH_SOCK and not its own socket

### ISSUE THREAD

**Issue by sadsimulation** [Foxboron/ssh-tpm-agent#36]
Hi, while setting this up I found that
```
ssh-tpm-agent --print-socket
```
does not return the correct value of `/run/user/1000/ssh-tpm-agent.sock` but rather the current value of `$SSH_AUTH_SOCK`,
which in my case pointed to the `gpg-agent.sock`.

I believe this should be fixed to correctly reflect the ssh-tpm-agent socket, so `export SSH_AUTH_SOCK=$(tpm-ssh-agent --print-socket)` works as expected.

**Comment by Foxboron** [comment]
This is expected behaviour. If you run with multiple ssh auth sockets please just specify the path.

**Comment by sadsimulation** [comment]
Understood, thanks for the clarification!
