### ISSUE TITLE
Change PIN

### ISSUE THREAD

**Issue by mutantmonkey** [Foxboron/ssh-tpm-agent#39]
Is it possible to change the PIN for a key, similar to ssh-keygen's `-p`? I don't see an option in ssh-tpm-keygen for this.

**Comment by Foxboron** [comment]
Currently not possible. But it should be fairly trivial to implement.

**Comment by FLX-0x00** [comment]
would love to see this feature =)

**Comment by Foxboron** [comment]
https://github.com/google/go-tpm/ needs to be extended to support `TPM2_ObjectChangeAuth` for this to be implemented.

I have patches locally for this but need to upstream them first.

**Comment by Foxboron** [comment]
`TPM2_ObjectChangeAuth` has been implemented here https://github.com/google/go-tpm/pull/354

**Comment by Foxboron** [comment]
Upstream PR has landed so I'll take a stab at this soon'ish.

**Comment by Foxboron** [comment]
`ssh-tpm-keygen -p` should work with the next release of `ssh-tpm-agent`.

https://github.com/Foxboron/ssh-tpm-agent/commit/2935df47bb97498fb3a6cdd68bf9573b90e4d055
