### ISSUE TITLE
0.3.0: default key length not valid

### ISSUE THREAD

**Issue by grawity** [Foxboron/ssh-tpm-agent#42]
Docs say that ECDSA P-256 is the default if neither `-t` nor `-b` is not specified, but that doesn't seem to be the case:

```
$ ssh-tpm-keygen
2024/02/26 11:12:10 invalid ecdsa key length: TPM does not support 0 bits

$ ssh-tpm-keygen -t ecdsa
2024/02/26 11:16:39 invalid ecdsa key length: TPM does not support 0 bits
```

Specifying `-t rsa` without `-b` seems to correctly generate a 2048-bit RSA key.

**Comment by FLX-0x00** [comment]
same on my end. specifying the -b parameter works

```bash
❯ ssh-tpm-keygen
2024/02/27 18:34:59 invalid ecdsa key length: TPM does not support 0 bits
❯ ssh-tpm-keygen -b 256
Generating a sealed public/private ecdsa key pair.
Enter file in which to save the key (/home/XXXX/.ssh/id_ecdsa): 
```

**Comment by FLX-0x00** [comment]
Maybe a small upgrade guide should be placed in the release notes for users who has already used the other keys =) for me works removing the .tpm file, reimport with ssh-tpm-keygen --import id_ecdsa -b 256

**Comment by Foxboron** [comment]
@FLX-0x00 Lol, what? Does that actually work?

**Comment by FLX-0x00** [comment]
Yes. was wondering what if i specify my own key leng....yep. works. maybe there is also something wrong with the parser. =) happy to help

**Comment by FLX-0x00** [comment]
Because the error was the same in the import i tried it out with -b and now I can use ssh again =) I converted all my ssh stuff to this tool, so I was really in a rush to get this running again :D

**Comment by Foxboron** [comment]
That shouldn't work. The `--import` code literally parses the secret parts of the key out of an existing ssh formatted private key.

I suspect you are accidentally importing your old `id_ecdsa` key.

**Comment by FLX-0x00** [comment]
I added my "old" key again yes. The key is ecdsa-sha2-nistp256

**Comment by FLX-0x00** [comment]
> That shouldn't work. The `--import` code literally parses the secret parts of the key out of an existing ssh formatted private key.
> 
> I suspect you are accidentally importing your old `id_ecdsa` key.

Of course I have made a backup before sealing the key with the .tpm extension. So I removed the old .tpm file, and imported my backup key again. now the "new" sealed key works with the agent. Was it wrong?

**Comment by Foxboron** [comment]
> Of course I have made a backup before sealing the key with the .tpm extension. So I removed the old .tpm file, and imported my backup key again. now the "new" sealed key works with the agent. Was it wrong?

No it only confused me how you where re-importing the key. But all good.

**Comment by FLX-0x00** [comment]
Hard to hear from the owner of the repo but hey, if you need anything that helps on debugging this stuff just hit me here. I will provide everything except the apored output of my private key ;)
