### ISSUE TITLE
Support SSH_ASKPASS

### ISSUE THREAD

**Issue by nl6720** [Foxboron/ssh-tpm-agent#47]
I would be nice if `$SSH_ASKPASS` could be used for TPM key PIN entry in place of `pinentry`.

Most ssh users are likely to be familial with ssh askpass programs, but may not be so familiar with pinentry from the GnuPG world.

**Comment by Foxboron** [comment]
Fixed with https://github.com/Foxboron/ssh-tpm-agent/commit/13e956cbd568e6f861bf7cafd507d40329bab1fe

**Comment by dcousens** [comment]
Hi @Foxboron, I don't think https://github.com/Foxboron/ssh-tpm-agent/commit/2ceaef3a502c01b50840b4e840f9b80c6b156ad6 is released

**Comment by Foxboron** [comment]
Yep, I haven't cut a new release as I've been deep into figuring out how a TPM based CA authority could be written.
