### ISSUE TITLE
Error when running `ssh-tpm-keygen`: `open /dev/tpmrm0: permission denied`

### ISSUE THREAD

**Issue by BellaCoola** [Foxboron/ssh-tpm-agent#49]
Hello, when I try to run the `ssh-tpm-keygen` command, I get the following error: `open /dev/tpmrm0: permission denied`. Is the user executing the command expected to have some special permissions and / or is the user expected to belong to some group (e.g. `tss` group)?

Thank you very much and have a nice day!

**Comment by Foxboron** [comment]
You need to be part of the `tss` group, but the implementation depends on your distribution.

**Comment by Foxboron** [comment]
I'll close this issue if there isn't more to it.
