### ISSUE TITLE
How to delete key?

### ISSUE THREAD

**Issue by hellesvik** [Foxboron/ssh-tpm-agent#52]
I am trying to delete a key, but it does not work.
Key was added with ssh-tpm-keygen, and it shows up when I do ssh-add -L.
I tried ssh-add  placeholder.tpm, which returns:
> Bad key file tpm_hellesvik_gitlab.tpm: No such file or directory

And ssh-tpm-add -d placeholder.tpm, which returns:
> 2024/05/24 17:39:06 open -d: no such file or directory

ssh-tpm-agent.service gives me
> agent 17: operation unsupported

**Comment by hellesvik** [comment]
Arch Linux, installed via pacman

**Comment by Foxboron** [comment]
Fixd, `ssh-add -d` should work now.
