### ISSUE TITLE
`ssh-tpm-keygen -A` returns ECDSA unsupported

### ISSUE THREAD

**Issue by enihcam** [Foxboron/ssh-tpm-agent#65]
version 0.6.0

```bash
/etc/ssh # ssh-tpm-keygen --supported
ecdsa bit lengths: 256
rsa bit lengths: 2048

/etc/ssh # ssh-tpm-keygen -A
2024/10/05 17:36:23 INFO Generating new host key algorithm=ECDSA
2024/10/05 17:36:23 unsupported key type

/etc/ssh # ls *.tpm
ssh_tpm_host_rsa_key.tpm
```

as you see, only RSA key is generated.

**Comment by Foxboron** [comment]
Interesting!

Does creating a normal key work?

**Comment by enihcam** [comment]
> Interesting!
> 
> Does creating a normal key work?

yes, both creating and importing an ecdsa key work as normal.

**Comment by Foxboron** [comment]
I didn't change `TPMAlgECDSA` to `TPMAlgECC` when clearing up the code in `go-tpm-keyfiles`. Pushed a fix now that should generate it properly.
