### ISSUE TITLE
Git Signing

### ISSUE THREAD

**Issue by rawkode** [Foxboron/ssh-tpm-agent#66]
I've tried pointing `SSH_AUTH_SOCK` to the tpm-ssh-agent socket, but Git commit signing doesn't appear to work; it hangs forever.

Using `GIT_TRACE=1` I can see it's running

`ssh-keygen -Y sign -n git -f /home/rawkode/.ssh/tpm2.pub`

Should this work?

**Comment by Foxboron** [comment]
I've tested this previously and it did work. But there are not tests for it so I might have broken it at some point.

**Comment by rawkode** [comment]
My config, in-case you're able to spot something obvious that is incorrect.

```shell
❯ echo $SSH_AUTH_SOCK
/run/user/1000/ssh-tpm-agent.sock
```

```shell
cat ~/.config/git/config
[commit]
        gpgSign = true
[gpg]
        format = "ssh"
        program = "/nix/store/65lafl8zxvwslpg2dlpxz1wlxnf11scv-gnupg-2.4.5/bin/gpg2"
[gpg "ssh"]
        allowedSignersFile = "~/.config/git/allowed_signers"
[user]
        signingKey = "/home/rawkode/.ssh/tpm2.pub"
```

**Comment by rawkode** [comment]
I confirmed that the SSH agent is working fine:

```shell
❯ ssh git@github.com
Enter PIN for 'rawkode':
PTY allocation request failed on channel 0
Hi rawkode! You've successfully authenticated, but GitHub does not provide shell access.
Connection to github.com closed.
```

**Comment by rawkode** [comment]
Using `strace`, I can see that `ssh-keygen` is waiting for a response from the `ssh-tpm-agent.sock`:

```shell
write(2, "debug3: ssh_get_authentication_s"..., 86debug3: ssh_get_authentication_socket_path: path '/run/user/1000/ssh-tpm-agent.sock'
) = 86
socket(AF_UNIX, SOCK_STREAM, 0)         = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/user/1000/ssh-tpm-agent.sock"}, 110) = 0
write(3, "\0\0\0\1", 4)                 = 4
write(3, "\v", 1)                       = 1
read(3,
```

**Comment by Foxboron** [comment]
Seems like a bug. Thanks, I'll try to take a look at this at some point!

**Comment by rawkode** [comment]
I ran `ssh-tpm-keygen` again and it's working now.

I'm not sure what I did differently, but I'll assume this was user error.

Sorry
