### ISSUE TITLE
Authentication failed with private GitHub organization

### ISSUE THREAD

**Issue by filvuk** [Foxboron/ssh-tpm-agent#69]
I've faced an issue cloning a private organization repository, and would like to document the solution here for future reference, and for others facing the same problem and searching the issues for keywords.

I had a ssh configuration file for use of multiple simultaneous keys set up as follows:

```
Host *
  IdentityAgent $SSH_AUTH_SOCK

Host name1
  HostName github.com
  User git
  IdentityFile ~/.ssh/name1.tpm

Host name2
  HostName github.com
  User git
  IdentityFile ~/.ssh/name2.tpm
```
This setup worked for public and private repositories on all of my accounts, but it didn't work for private (or public, haven't tested) repositories in organizations, trying to clone would simply fail with `ERROR: Repository not found.`. 

The solution was to simply use public keys as values of the IdentityFile keywords instead of private keys. I am unsure as to why this resolved the issue. My suspicion is that the wrong private key was being read during authentication. From the [ssh_config man page](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html), it almost reads as though ssh-agent is only used when supplying a public and not a private key. But then again, I don't understand why the config worked for my personal accounts, while for the organization it failed. Since my knowledge about ssh authentication in GitHub and TPMs is limited, I'd greatly appreciate someone offering an explanation.

Also, I've found that in the [ssh-config section](https://github.com/Foxboron/ssh-tpm-agent?tab=readme-ov-file#ssh-config) identity leakage is mentioned. While reading the [ssh_config man page](https://www.man7.org/linux/man-pages/man5/ssh_config.5.html), I've found the `IdentitiesOnly` keyword, which ensures that:

> ssh(1) should only use the configured authentication identity and certificate files (either the default files, or those explicitly configured in the ssh_config files or passed on the ssh(1) command-line), even if ssh-agent(1) or a PKCS11Provider or SecurityKeyProvider offers more identities.

This would strengthen identity leakage prevention, if I understand correctly.

I will close this after I submit, but feel free to reopen if needed.

**Comment by Foxboron** [comment]
> IdentityFile ~/.ssh/name2.tpm

This will never work as SSH doesn't recognize the key files `ssh-tpm-agent` produces. If this didn't give you an explicit error another key was used.

Also see the bottom of the README file: https://github.com/Foxboron/ssh-tpm-agent?tab=readme-ov-file#ssh-config

**Comment by derlade** [comment]
> This will never work as SSH doesn't recognize the key files ssh-tpm-agent produces. If this didn't give you an explicit error another key was used.

That is interesting, since this was a fresh install, so no other keys other than the ones generated by `ssh-tpm-keygen` are or were ever present. It must have worked somehow, since I could pull from and push to my private repositories without issue.

**Comment by filvuk** [comment]
> This will never work as SSH doesn't recognize the key files ssh-tpm-agent produces. If this didn't give you an explicit error another key was used.

That is interesting, since this was a fresh install, so no other keys other than the ones generated by ssh-tpm-keygen are or were ever present. It must have worked somehow, since I could pull from and push to my private repositories without issue.

**Comment by Foxboron** [comment]
```
λ ~ » ssh -i .ssh/id_ecdsa.tpm git@github.com
Load key ".ssh/id_ecdsa.tpm": error in libcrypto
```

it shouldn't. So this is as far as I'm concerned expected behaviour. I'm guessing you have `id_rsa`, `id_ed25519` og `id_ecdsa` in `~/.ssh` which `ssh` is going to fallback too.
