### ISSUE TITLE
ssh-tpm-agent: Unable to find private key when using SSH certificate for git commit signing

### ISSUE THREAD

**Issue by andsens** [Foxboron/ssh-tpm-agent#80]
This git config
```
$ cat .gitconfig
[user]
  signingKey = /home/aim/.ssh/id_ecdsa.pub
```

works exactly as expected when using `ssh-tpm-agent`. However when using certificates for signing commits with
```
[user]
  signingKey = /home/aim/.ssh/id_ecdsa-cert.pub
```
the agent fails with
```
time=2024-12-17T16:27:23.307+01:00 level=DEBUG msg="called list"
time=2024-12-17T16:27:23.307+01:00 level=DEBUG msg="called signwithflags"
time=2024-12-17T16:27:23.307+01:00 level=DEBUG msg="trying to sign as proxy..."
time=2024-12-17T16:27:23.308+01:00 level=INFO msg="agent 13: no private keys match the requested public key"
```

I'm guessing this part https://github.com/Foxboron/ssh-tpm-agent/blob/b9b17a988493f53a010fc4a75143f383b8201291/agent/agent.go#L193-L197 needs to look for certificates as well?

If ssh signing is anything like x509 signing you should get the entire tbs/ToBeSigned payload submitted and just sign that as usual. Then git attaches the certificate to the signature, meaning that *should* be all there is to it. So my guess is the issue simply stems from git not attaching the certificate if you don't specify one as the signingKey. (loads of assumptions here, don't take my word for anything I just said ;-) )

p.s.: I'm bombarding you with new issues right now, sorry about that :laughing:. Let me know if I can help you with any of the fixes or do some research for you. I'm heading for vacation today but can work on it in the new year.

**Comment by andsens** [comment]
Huh, ok. Seems like go crypto itself is a bit annoying with the types: https://pkg.go.dev/golang.org/x/crypto/ssh/agent#Agent
Shouldn't there be an interface for both pubkeys and certificates in that `Sign()` method signature?  
AFAICT this https://github.com/Foxboron/ssh-tpm-agent/blob/b9b17a988493f53a010fc4a75143f383b8201291/agent/agent.go#L194-L196 should check if `key` is a certificate and marshal its public key instead, right? I'm somewhat a beginner regarding go and go types, so I'm not quite sure how to try this out myself.

**Comment by Foxboron** [comment]
> p.s.: I'm bombarding you with new issues right now, sorry about that 😆. Let me know if I can help you with any of the fixes or do some research for you. I'm heading for vacation today but can work on it in the new year.

No worries. I deal with things when I feel like it so feel free to create issues and stuff when you discover things and/or have questions. I'll get to it at some point :)

**Comment by Foxboron** [comment]
Pushed an ammended commit to fix this issue. Thanks!

**Comment by Foxboron** [comment]
You might have discovered it already, but it turns out your solution was the correct one and I implemented the wrong solution :)

I've submitted a patch upstream to try and fix this properly instead of doing the `Marshal()` and `ParsePublicKey()` dance.

https://github.com/golang/crypto/pull/307
